from paymentech.models.base import DataField, PaymentechModel


class Order(PaymentechModel):
    order_id = DataField("OrderID", max_length=22)
    industry_type = DataField("IndustryType", default="EC", max_length=2)
    message_type = DataField("MessageType", default="AC", max_length=2)
    payment_action = DataField("PaymentActionInd", max_length=1)
    terminal_id = DataField("TerminalID", default="001", max_length=3)
    card_brand = DataField("CardBrand", max_length=2)
    account_number = DataField("AccountNum", max_length=19)
    expiration = DataField("Exp", max_length=6)
    currency_code = DataField("CurrencyCode", default="840", max_length=3)
    currency_exponent = DataField("CurrencyExponent", default="2", max_length=6)
    card_security_indicator = DataField("CardSecValInd", max_length=1)
    card_security_value = DataField("CardSecVal", max_length=4)
    bank_routing_number = DataField("BCRtNum", max_length=9)
    check_dda = DataField("CheckDDA", max_length=17)
    bank_account_type = DataField("BankAccountType", max_length=1)
    ecp_authorization_method = DataField("ECPAuthMethod", default="I", max_length=1)
    ecp_payment_delivery_method = DataField("BankPmtDelv", default="B", max_length=1)
    ecp_action_code = DataField("ECPActionCode", max_length=2)
    ecp_check_serial_number = DataField("ECPCheckSerialNumber", max_length=9)
    ecp_terminal_city = DataField("ECPTerminalCity", max_length=4)
    ecp_terminal_state = DataField("ECPTerminalState", max_length=2)
    ecp_image_reference = DataField("ECPImageReferenceNumber", max_length=32)
    customer_email = DataField("CustomerEmail", max_length=50)
    customer_email_type = DataField("EmailAddressSubtype", max_length=1)
    customer_browser_name = DataField("CustomerBrowserName", max_length=60)
    customer_ip_address = DataField("CustomerIpAddress", max_length=45)
    address1 = DataField("AVSaddress1", max_length=30)
    address2 = DataField("AVSaddress2", max_length=30)
    city = DataField("AVScity", max_length=20)
    state = DataField("AVSstate", max_length=2)
    zip = DataField("AVSzip", max_length=10)
    phone_number = DataField("AVSphoneNum", max_length=14)
    phone_number_type = DataField("AVSPhoneType", max_length=1)
    cardholder_name = DataField("AVSname")
    country_code = DataField("AVScountryCode", default="US", max_length=2)
    shipping_method = DataField("ShippingMethod", max_length=1)
    destination_zip = DataField("AVSDestzip", max_length=10)
    destination_address1 = DataField("AVSDestzip", max_length=30)
    destination_address2 = DataField("AVSDestaddress2", max_length=28)
    destination_city = DataField("AVSDestcity", max_length=20)
    destination_state = DataField("AVSDeststate", max_length=2)
    destination_phone_number = DataField("AVSDestphoneNum", max_length=14)
    destination_phone_type = DataField("AVSDestPhoneType", max_length=1)
    destination_name = DataField("AVSDestname", max_length=30)
    destination_country_code = DataField("AVSDestcountryCode", default="US", max_length=2)
    customer_profile_method = DataField("CustomerProfileFromOrderInd", max_length=5)
    customer_reference_number = DataField("CustomerRefNum", max_length=22)
    customer_automatic_number_identification = DataField("CustomerAni", max_length=10)
    customer_profile_order_override_method = DataField("CustomerProfileOrderOverrideInd", default="NO", max_length=2)
    customer_token_indicator = DataField("DPANInd", max_length=1)
    status = DataField("Status", max_length=2)
    authentication_eci_indicator = DataField("AuthenticationECIInd", max_length=2)
    cavv = DataField("CAVV", max_length=70)
    aav = DataField("AAV", max_length=32)
    xid = DataField("XID", max_length=40)
    aevv = DataField("AEVV", max_length=56)
    prior_authorization_identifier = DataField("PriorAuthID", max_length=6)
    amount = DataField("Amount", max_length=12)
    comments = DataField("Comments", max_length=256)
    shipping_reference = DataField("ShippingRef", max_length=40)
    tax_type = DataField("TaxInd", max_length=1)
    tax = DataField("Tax", max_length=12)
    amex_transaction_advice_addendum1 = DataField("AMEXTranAdvAddn1", max_length=40)
    amex_transaction_advice_addendum2 = DataField("AMEXTranAdvAddn2", max_length=40)
    amex_transaction_advice_addendum3 = DataField("AMEXTranAdvAddn3", max_length=40)
    amex_transaction_advice_addendum4 = DataField("AMEXTranAdvAddn4", max_length=40)
    soft_descriptor_merchant = DataField("SDMerchantName", max_length=25)
    soft_descriptor_product = DataField("SDProductDescription", max_length=18)
    soft_descriptor_city = DataField("SDMerchantCity", max_length=13)
    soft_descriptor_phone = DataField("SDMerchantPhone", max_length=13)
    soft_descriptor_url = DataField("SDMerchantURL", max_length=13)
    soft_descriptor_email = DataField("SDMerchantEmail", max_length=13)
    recurring_indicator = DataField("RecurringInd", max_length=2)
    euro_debit_country_code = DataField("EUDDCountryCode", max_length=2)
    euro_debit_bank_sort_code = DataField("EUDDBankSortCode", max_length=10)
    euro_debit_rib = DataField("EUDDRibCode", max_length=2)
    biller_reference = DataField("BillerReferenceNumber", max_length=25)
    managed_billing_type = DataField("MBType", max_length=1)
    managed_billing_order_id_generation_method = DataField("MBOrderIdGenerationMethod", max_length=2)
    managed_billing_start_date = DataField("MBRecurringStartDate", max_length=8)
    managed_billing_end_date = DataField("MBRecurringEndDate", max_length=8)
    managed_billing_no_end_date = DataField("MBRecurringNoEndDateFlag", max_length=1)
    managed_billing_max_billings = DataField("MBRecurringMaxBillings", max_length=6)
    managed_billing_frequency = DataField("MBRecurringFrequency", max_length=64)
    managed_billing_deferred_bill_date = DataField("MBDeferredBillDate", max_length=8)
    transaction_reference_number = DataField("TxRefNum", max_length=40)
    purchase_order_number = DataField("PCOrderNum", max_length=17)
    purchase_order_name = DataField("PCDestName", max_length=30)
    purchase_order_address1 = DataField("PCDestAddress1", max_length=30)
    purchase_order_address2 = DataField("PCDestAddress2", max_length=30)
    purchase_order_city = DataField("PCDestCity", max_length=20)
    purchase_order_state = DataField("PCDestState", max_length=2)
    purchase_order_zip = DataField("PCDestZip", max_length=10)
    partial_auth_indicator = DataField("PartialAuthInd", max_length=1)
    account_updater_eligibility = DataField("AccountUpdaterEligibility", default="Y", max_length=1)
    use_stored_aav_indicator = DataField("UseStoredAAVInd", max_length=1)
    # NOTE: Skipping all Level 3 transaction elements and a significant number of other elements for now

    class Meta:
        wrapper = "NewOrder"
