name: Test and Publish
on: push

jobs:
  static:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/ruff-action@v3

  tests:
    name: Automated Testing
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install requirements
        run: pip install -r requirements_tests.txt

      - name: Run pytest
        run: pytest

  publish:
    name: Publish to PyPI
    if: contains(github.ref, 'tags/')
    needs: [static, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build
        run: |
          pip install setuptools wheel twine
          python3 setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
